name: Run Selenium Tests
on:
#  push:
#    branches:
#      - developer
#  pull_request:
#    branches:
#      - developer
  workflow_dispatch: null
jobs:
  Build-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U pytest selenium
      - name: Run tests with pytest
        run: pytest  --capture=no --verbose selenium_checks.py
